version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:django
    container_name: kenwin-container
    command: python kenwinproject/manage.py runserver 0.0.0.0:8000
  migration:
    build: .
    image: app:django
    volumes:
      - .:/app
    command: python kenwinproject/manage.py migrate