version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:django
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    container_name: kenwin-app
    command: python kenwinproject/manage.py runserver 0.0.0.0:8000
    networks:
      - localnetwork

  migration:
    build: .
    image: app:django
    volumes:
      - .:/app
    command: python kenwinproject/manage.py migrate
    networks:
      - localnetwork
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    networks:
      - localnetwork

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local

networks:
  localnetwork:
    name: kenwin-network
    driver: bridge
    