# Generated by Django 4.0.6 on 2022-07-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('enterprice', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=50, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
